# Generated by Django 3.2.6 on 2022-03-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='storedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('desription', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='image')),
            ],
        ),
    ]
