# Generated by Django 3.2.6 on 2022-03-04 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cstoreapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storedb',
            old_name='desription',
            new_name='description',
        ),
    ]
