# Generated by Django 3.2.6 on 2022-03-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cstoreapp', '0002_rename_desription_storedb_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='productdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100, null=True)),
                ('weight', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('image', models.ImageField(null=True, upload_to='image')),
            ],
        ),
    ]
