# Generated by Django 3.2.6 on 2022-03-04 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cstoreapp', '0003_productdb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdb',
            old_name='productname',
            new_name='pname',
        ),
    ]
